### ISSUE TITLE
O-DT-TA-1-012 : Tactics instruments unique identification

### ISSUE THREAD

**Issue by canne** [canne/dashboard_tactics_pi#25]
Tactics shall identify itself with a leading up-arrow (" \u2191") when it creates an instrument showing active values using Dashboard instrument classes or classes which derives from those.

**Comment by canne** [comment]
This discussion was originally started by @rgleason and @scadaperspective - please comment test and comment usability and ergonomics of the below solution, if you like, thank you!

In fact the ^  and unicode (caret "\u2038") are not the same, the latter is actually a tiny small character, barely visible. I replaced it with an up arrow \u2191. Details of the implemenation are here https://github.com/canne/dashboard_tactics_pi/commit/120bd102f9e7ee03b68ba34876fec7c9e34acfc9 . It is portable at least between Windows and Linux and renders like this:
<img width="80" alt="2019-07-04_000612_unicode_in" src="https://user-images.githubusercontent.com/6381128/60629017-4bc08500-9df4-11e9-982b-0a6d359dde9f.png">
and is displayed systematically on every instrument or function provided by Tactics. If no comments and/or a counter suggestion, I retain this solution after ten days from this message.

**Comment by rgleason** [comment]
Great solution. Thank you Petri!

**Comment by scadaperspective** [comment]
Up Arrow works on macOS

**Comment by scadaperspective** [comment]
Cross platform to macOS is ok as well.
