### ISSUE TITLE
Polar::GetPolarSpeed() NaN check typo at return [D19]

### ISSUE THREAD

**Issue by canne** [canne/dashboard_tactics_pi#58]
<p>Instead of ` return ((std::isnan(avspd1) || std::isnan(avspd1))?NAN: avspd1 + (avspd2 - avspd1)*fws); ` it should read ` return ((std::isnan(avspd1) || std::isnan(avspd2))?NAN: avspd1 + (avspd2 - avspd1)*fws); `</p>

**Comment by canne** [comment]
Hi @tom-r, a minor typo I found while testing with Sean's example polars. If you like, I'll report also in your repo for your memo. Meanwhile, I continue tests with the change.

**Comment by tom-r** [comment]
Thanks Petri,
good catch. Fixed it in the original tactics_pi repo.
Thomas

**Comment by canne** [comment]
Created and linked to requirement #61 - preparation for fix commit., regression test reference [TC58](https://canne.testquality.com/project/7362/testcase/182178).

**Comment by canne** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D19. Do not remove or edit.` [D19](https://canne.testquality.com/project/7362/result/1318854/defect/4647)
