### ISSUE TITLE
No Issue, tried it out.

### ISSUE THREAD

**Issue by rgleason** [canne/dashboard_tactics_pi#65]
I tried 3.0003 today for a short while, not like your testing.
The arrows show up nicely.  Tried to get layline showing,, perhaps I need to restarrt it?
Selected new polars, tried to toggle on and off etc.  They were working before.

Ah ah they are off in  preferences  now working.
I don't see a single parameter that is blank...  

![Screenshot (6)](https://user-images.githubusercontent.com/2363959/62013775-653fbd00-b165-11e9-9702-b75be2290bc6.png)

**Comment by canne** [comment]
Ready to complete 0.3.005, closing this one. Should be available in few minutes.
