### ISSUE TITLE
Moon phase and sunrise/sunset instruments not working

### ISSUE THREAD

**Issue by SCarns** [canne/dashboard_tactics_pi#93]
Discovered that the sunrise/sunset and Moon Phase don't work, but do work in Dashboard. See attached screen shot. Floating window is Dashboard & fixed gauges on right are Dash_T.

![Screen Shot 2019-11-21 at 2 32 49 PM](https://user-images.githubusercontent.com/39605258/69382723-a6a42d00-0c6c-11ea-8ccb-6c3b2ea70a2e.png)

**Comment by canne** [comment]
Fixed (tested with simulator so GPS time is funny in this screenshot):
<img width="307" alt="Annotation 2019-11-22 004629" src="https://user-images.githubusercontent.com/6381128/69386179-1f81a400-0cc2-11ea-82f4-5b107eedc59c.png">

**Comment by SCarns** [comment]
Perfect. Thanks.
